# Where things are
source: .
destination: ./_site
collections_dir: .
theme: beautiful-jekyll

# Handling Reading
safe: true

# Conversion
lsi: false
incremental: false
highlighter: rouge

# Markdown Processors
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Other
gist:
  noscript: false
plugins:
  - jemoji
